evaluation-frontend:
    container_name: giphy-frontend
    build: ./
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development