export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';


// Category action types
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_FAVORITE_TO_CATEGORY = 'ADD_FAVORITE_TO_CATEGORY';


// GIPHY ACTION TYPES
export const FETCH_GIPHY_REJECTED = 'FETCH_GIPHY_REJECTED';
export const FETCH_GIPHY_FULFILLED = 'FETCH_GIPHY_FULFILLED';